export const TOWERS = [
  {
    id: "autocannon",
    name: "Autocannon",
    cost: 90,
    power: 2,
    range: 10,
    damage: 15,
    rate: 0.32,
    role: "Rapid kinetic fire · ground & air",
    color: 0xd3b47c,
    branches: ["Sabot · armor penetration", "Cyclone · faster fire"],
  },
  {
    id: "railgun",
    name: "Railgun",
    cost: 180,
    power: 4,
    range: 17,
    damage: 100,
    rate: 2.3,
    role: "Piercing line · armored targets",
    color: 0x96c2cf,
    branches: ["Lance · double damage", "Repeater · faster fire"],
  },
  {
    id: "missile",
    name: "Missile battery",
    cost: 145,
    power: 3,
    range: 14,
    damage: 45,
    rate: 1.6,
    splash: 3,
    role: "Explosive area · ground & air",
    color: 0xceaa70,
    branches: ["Cluster · larger blasts", "Barrage · faster fire"],
  },
  {
    id: "flak",
    name: "Flak battery",
    cost: 130,
    power: 3,
    range: 12,
    damage: 24,
    rate: 0.55,
    splash: 2,
    role: "Air priority · fragmentation",
    color: 0xb6c5a3,
    branches: ["Shrapnel · larger blasts", "Interceptor · faster fire"],
  },
  {
    id: "incinerator",
    name: "Incinerator",
    cost: 120,
    power: 3,
    range: 6,
    damage: 16,
    rate: 0.2,
    splash: 2.2,
    role: "Short range · heat & area damage",
    color: 0xe99d66,
    branches: ["Inferno · larger blasts", "Pressure · faster fire"],
  },
  {
    id: "arc",
    name: "Arc emitter",
    cost: 170,
    power: 5,
    range: 9,
    damage: 30,
    rate: 0.85,
    chain: 4,
    role: "Chain discharge · clustered enemies",
    color: 0x8abcc9,
    branches: ["Conduit · more chains", "Capacitor · faster fire"],
  },
  {
    id: "cryo",
    name: "Cryo projector",
    cost: 100,
    power: 2,
    range: 9,
    damage: 9,
    rate: 0.6,
    slow: 2,
    role: "Movement suppression · ground & air",
    color: 0xa4cbd4,
    branches: ["Permafrost · area slow", "Compression · faster fire"],
  },
  {
    id: "mortar",
    name: "Mortar",
    cost: 160,
    power: 3,
    range: 20,
    damage: 65,
    rate: 2.5,
    splash: 4,
    role: "Indirect bombardment · ground",
    color: 0xc8ae87,
    branches: ["Seismic shell · larger blasts", "Autoloader · faster fire"],
  },
  {
    id: "drone",
    name: "Drone hangar",
    cost: 190,
    power: 4,
    range: 16,
    damage: 22,
    rate: 0.55,
    role: "Mobile interceptors · ground & air",
    color: 0xb6c7bd,
    branches: ["Heavy drones · damage", "Swarm bay · faster fire"],
  },
  {
    id: "seismic",
    name: "Seismic driver",
    cost: 150,
    power: 4,
    range: 8,
    damage: 35,
    rate: 1.5,
    splash: 4,
    role: "Burrow disruption · vibration",
    color: 0xc7a26e,
    branches: ["Faultline · larger shockwave", "Resonance · faster fire"],
  },
];
export const SUPPORT = [
  {
    id: "mine",
    name: "Mining rig",
    cost: 100,
    power: 2,
    role: "Alloy income · strong vibration",
  },
  {
    id: "generator",
    name: "Power plant",
    cost: 100,
    power: 0,
    role: "+12 power capacity · priority target",
  },
  {
    id: "heat",
    name: "Heat decoy",
    cost: 60,
    power: 1,
    role: "Attracts heat hunters",
  },
  {
    id: "vibration",
    name: "Seismic lure",
    cost: 60,
    power: 1,
    role: "Attracts vibration hunters",
  },
];
export const ENEMIES = [
  { name: "Skitter", hp: 45, speed: 3.2, damage: 7, signal: "vibration" },
  {
    name: "Bastion",
    hp: 220,
    speed: 1.3,
    damage: 16,
    armor: 0.45,
    signal: "heat",
  },
  { name: "Razor", hp: 65, speed: 4.5, damage: 9, signal: "heat" },
  {
    name: "Burrower",
    hp: 110,
    speed: 2.3,
    damage: 12,
    burrow: true,
    signal: "vibration",
  },
  {
    name: "Climber",
    hp: 90,
    speed: 2.8,
    damage: 10,
    climb: true,
    signal: "heat",
  },
  { name: "Wasp", hp: 75, speed: 3.3, damage: 9, flying: true, signal: "heat" },
  {
    name: "Artillery",
    hp: 140,
    speed: 1.4,
    damage: 18,
    ranged: 8,
    signal: "vibration",
  },
  {
    name: "Mender",
    hp: 105,
    speed: 2,
    damage: 6,
    healer: true,
    signal: "vibration",
  },
  {
    name: "Tracker",
    hp: 140,
    speed: 2.5,
    damage: 14,
    tracker: true,
    signal: "heat",
  },
  {
    name: "Brood carrier",
    hp: 260,
    speed: 1.3,
    damage: 15,
    brood: true,
    signal: "vibration",
  },
];
export const BOSSES = [
  {
    name: "THE FAULT EATER",
    hp: 3600,
    speed: 1.1,
    damage: 55,
    signal: "vibration",
    boss: 0,
  },
  {
    name: "THE WALKING SIEGE",
    hp: 4400,
    speed: 0.8,
    damage: 65,
    ranged: 10,
    signal: "heat",
    boss: 1,
  },
  {
    name: "THE BREACH QUEEN",
    hp: 4000,
    speed: 1.2,
    damage: 45,
    brood: true,
    signal: "vibration",
    boss: 2,
  },
];
export const FEATURE_NAMES = [
  "Seismic beacon",
  "Coolant vent",
  "Volatile deposit",
  "Power relay",
  "Fractured formation",
  "Salvage crawler",
];
